import Logo from "@/app/_components/Logo"
import Navgation from "@/app/_components/Navigation"
import "@/app/_styles/globals.css"
export const metadata = {
  title: 'The Wild Oasis',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-primary-950 text-primary-100 min-h-screen">
      <header>
      <Logo />
      <Navgation />
      </header>
      <main>
      {children}
      </main>
      <footer>Copyright by The Wild Oasis</footer>
      </body>
    </html>
  )
}
